/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_trimeshkit_meshprocessing_TriMeshAlgorithms */

#ifndef _Included_com_trimeshkit_meshprocessing_TriMeshAlgorithms
#define _Included_com_trimeshkit_meshprocessing_TriMeshAlgorithms

#include <TriMeshAlgorithms.h>
#include <TriMesh.h>
#include <NativeHandle.h>

#ifdef __cplusplus
extern "C" {
#endif
using namespace TriMeshKit::MeshProcessing;

/*
 * Class:     com_trimeshkit_meshprocessing_TriMeshAlgorithms
 * Method:    smooth
 * Signature: (Lcom/trimeshkit/meshprocessing/TriMesh;)Z
 */
JNIEXPORT bool JNICALL Java_com_trimeshkit_meshprocessing_TriMeshAlgorithms_smooth
  (JNIEnv * _env, jclass _class, jobject _mesh)
  {
	  TriMesh *inst = getHandle<TriMesh>(_env, _mesh);

      return TriMeshAlgorithms::smooth( *inst);

  }

#ifdef __cplusplus
}
#endif
#endif
